<Project>

	<PropertyGroup>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<UseArtifactsOutput>true</UseArtifactsOutput>
		<SatelliteResourceLanguages>en</SatelliteResourceLanguages>
	</PropertyGroup>

	<PropertyGroup>
		<DebugType>embedded</DebugType>
	</PropertyGroup>
	
</Project>