using System.Text.Json.Serialization;

namespace AIUsageMonitor.Core.Providers.Claude.Models;

/// <summary>
/// Represents aggregated activity metrics for a single calendar day.
/// </summary>
public sealed class DailyActivity
{
    /// <summary>
    /// Gets the calendar date the activity was recorded for.
    /// </summary>
    [JsonPropertyName("date")]
    [JsonConverter(typeof(DateOnlyJsonConverter))]
    public DateOnly Date { get; init; }

    /// <summary>
    /// Gets the total number of messages sent on this date.
    /// </summary>
    [JsonPropertyName("messageCount")]
    public int MessageCount { get; init; }

    /// <summary>
    /// Gets the total number of sessions started on this date.
    /// </summary>
    [JsonPropertyName("sessionCount")]
    public int SessionCount { get; init; }

    /// <summary>
    /// Gets the total number of tool calls made on this date.
    /// </summary>
    [JsonPropertyName("toolCallCount")]
    public int ToolCallCount { get; init; }
}

/// <summary>
/// Represents token usage broken down by model for a single calendar day.
/// </summary>
public sealed class DailyModelTokens
{
    /// <summary>
    /// Gets the calendar date the token usage was recorded for.
    /// </summary>
    [JsonPropertyName("date")]
    [JsonConverter(typeof(DateOnlyJsonConverter))]
    public DateOnly Date { get; init; }

    /// <summary>
    /// Gets the number of tokens consumed on this date, keyed by model name.
    /// </summary>
    [JsonPropertyName("tokensByModel")]
    public Dictionary<string, long> TokensByModel { get; init; } = [];
}

/// <summary>
/// Represents cumulative token usage and cost statistics for a single model.
/// </summary>
public sealed class ModelUsageEntry
{
    /// <summary>
    /// Gets the number of tokens used to create cache entries.
    /// </summary>
    [JsonPropertyName("cacheCreationInputTokens")]
    public long CacheCreationInputTokens { get; init; }

    /// <summary>
    /// Gets the number of tokens read from cache.
    /// </summary>
    [JsonPropertyName("cacheReadInputTokens")]
    public long CacheReadInputTokens { get; init; }

    /// <summary>
    /// Gets the maximum context window size, in tokens, supported by the model.
    /// </summary>
    [JsonPropertyName("contextWindow")]
    public int ContextWindow { get; init; }

    /// <summary>
    /// Gets the estimated cost, in US dollars, incurred by usage of this model.
    /// </summary>
    [JsonPropertyName("costUSD")]
    public decimal CostUSD { get; init; }

    /// <summary>
    /// Gets the total number of input tokens sent to the model.
    /// </summary>
    [JsonPropertyName("inputTokens")]
    public long InputTokens { get; init; }

    /// <summary>
    /// Gets the maximum number of output tokens the model is allowed to generate.
    /// </summary>
    [JsonPropertyName("maxOutputTokens")]
    public int MaxOutputTokens { get; init; }

    /// <summary>
    /// Gets the total number of output tokens generated by the model.
    /// </summary>
    [JsonPropertyName("outputTokens")]
    public long OutputTokens { get; init; }

    /// <summary>
    /// Gets the total number of web search requests made by the model.
    /// </summary>
    [JsonPropertyName("webSearchRequests")]
    public int WebSearchRequests { get; init; }
}

/// <summary>
/// Represents the cached, precomputed usage statistics for the Claude provider.
/// </summary>
public sealed class StatsCache
{
    /// <summary>
    /// Gets the list of daily activity records.
    /// </summary>
    [JsonPropertyName("dailyActivity")]
    public List<DailyActivity> DailyActivity { get; init; } = [];

    /// <summary>
    /// Gets the list of daily model token usage records.
    /// </summary>
    [JsonPropertyName("dailyModelTokens")]
    public List<DailyModelTokens> DailyModelTokens { get; init; } = [];

    /// <summary>
    /// Gets the timestamp of the earliest recorded session, if any.
    /// </summary>
    [JsonPropertyName("firstSessionDate")]
    public DateTimeOffset? FirstSessionDate { get; init; }

    /// <summary>
    /// Gets the number of messages sent, keyed by hour of day.
    /// </summary>
    [JsonPropertyName("hourCounts")]
    public Dictionary<string, int> HourCounts { get; init; } = [];

    /// <summary>
    /// Gets the date on which these statistics were last computed.
    /// </summary>
    [JsonPropertyName("lastComputedDate")]
    [JsonConverter(typeof(DateOnlyJsonConverter))]
    public DateOnly LastComputedDate { get; init; }

    /// <summary>
    /// Gets information about the longest recorded session, if any.
    /// </summary>
    [JsonPropertyName("longestSession")]
    public LongestSessionInfo? LongestSession { get; init; }

    /// <summary>
    /// Gets the usage statistics for each model, keyed by model name.
    /// </summary>
    [JsonPropertyName("modelUsage")]
    public Dictionary<string, ModelUsageEntry> ModelUsage { get; init; } = [];

    /// <summary>
    /// Gets the total number of messages recorded.
    /// </summary>
    [JsonPropertyName("totalMessages")]
    public int TotalMessages { get; init; }

    /// <summary>
    /// Gets the total number of sessions recorded.
    /// </summary>
    [JsonPropertyName("totalSessions")]
    public int TotalSessions { get; init; }

    /// <summary>
    /// Gets the schema version of the cached statistics.
    /// </summary>
    [JsonPropertyName("version")]
    public int Version { get; init; }
}

/// <summary>
/// Represents details about the longest recorded session.
/// </summary>
public sealed class LongestSessionInfo
{
    /// <summary>
    /// Gets the duration of the session, in milliseconds.
    /// </summary>
    [JsonPropertyName("duration")]
    public long Duration { get; init; }

    /// <summary>
    /// Gets the number of messages exchanged during the session.
    /// </summary>
    [JsonPropertyName("messageCount")]
    public int MessageCount { get; init; }

    /// <summary>
    /// Gets the unique identifier of the session.
    /// </summary>
    [JsonPropertyName("sessionId")]
    public string SessionId { get; init; } = "";

    /// <summary>
    /// Gets the timestamp at which the session occurred.
    /// </summary>
    [JsonPropertyName("timestamp")]
    public string Timestamp { get; init; } = "";
}